export const LABELS = {
  title: "نموذج تسجيل بيانات",
  fullName: "الاسم الكامل",
  idNumber: "رقم الهوية",
  phone: "رقم الهاتف",
  gender: "الجنس",
  male: "ذكر",
  female: "أنثى",
  placeholderName: "أدخل الاسم الكامل",
  placeholderID: "أدخل رقم الهوية المكون من 14 رقمًا",
  placeholderPhone: "أدخل رقم الهاتف المكون من 11 رقمًا",
  save: "حفظ البيانات",
  download: "تحميل ملف اكسل",
  registerTitle: "تسجيل بيانات جديدة",
  footer: "أمانة الإسكندرية حزب مستقبل وطن - امانة شباب قسم منتزة اول 2025",
  dataTable: "البيانات المسجلة",
  tableNum: "#",
  noData: "لا توجد بيانات مسجلة بعد",
  enterPassword: "أدخل كلمة المرور",
  submit: "تسجيل الدخول",
  wrongPassword: "كلمة المرور غير صحيحة"
};
