// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvwdwjztkdfyoldpxopj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2d2R3anp0a2RmeW9sZHB4b3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzAwMzAsImV4cCI6MjA2MTM0NjAzMH0.POam6dY93261hYSgx5yNR8piuVxjQ7KzG0WDIE6mmY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);